services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/media